In [48]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [96]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import time

Name = [] 

location = []

Ratings = []

pagenum = []

Reviews = []

Salaries = []

Interviews = []
jobs = []
Benifits = []
Awards = []

total_time = time.time()
for i in range(1, 11): 

    start_time = time.time()

   
    url = f"https://www.ambitionbox.com/companies-in-hyderabad?page={i}"

    headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    }

    response = requests.get(url, headers=headers)

    

    soup = BeautifulSoup(response.text, "html.parser")

    for x in soup.find_all('div', attrs={'class':'companyCardWrapper'}):

        name_tag = x.find('a', attrs={"class":"companyCardWrapper__companyName"})

        location_tag = x.find('span', attrs={'class':'companyCardWrapper__interLinking'})
        
        rat_tag = x.find('div', attrs={'class':'companyCardWrapper__companyRatingWrapper'})   # discounted price

        reviews_tag = x.find('span', attrs={'class':'companyCardWrapper__ActionCount'})

        salaries_tag = x.find('span', attrs={'class':'companyCardWrapper__ActionCount'})

        interviews_tag = x.find('span',attrs={'class':'companyCardWrapper__ActionCount'})
        job_tag = x.find('span',attrs={'class':'companyCardWrapper__ActionCount'})
        benifits_tag =  x.find('span',attrs={'class':'companyCardWrapper__ActionCount'})
        award_tag = x.find('div', attrs = {'class':"award-leaf"})
        

        Name.append(name_tag.text.strip() if name_tag else np.nan)

        Ratings.append(rat_tag.text.strip() if rat_tag else np.nan)

        location.append(location_tag.text.strip() if location_tag else np.nan)
        
        Awards.append(award_tag.text.strip() if award_tag else np.nan)
        action_counts = x.find_all('span', class_='companyCardWrapper__ActionCount')

        # Safe extraction (some cards may not have all 5)
        reviews = action_counts[0].text.strip() if len(action_counts) > 0 else np.nan
        salaries = action_counts[1].text.strip() if len(action_counts) > 1 else np.nan
        interviews = action_counts[2].text.strip() if len(action_counts) > 2 else np.nan
        job_count = action_counts[3].text.strip() if len(action_counts) > 3 else np.nan
        benefits = action_counts[4].text.strip() if len(action_counts) > 4 else np.nan

        Reviews.append(reviews)
        Salaries.append(salaries)
        Interviews.append(interviews)
        jobs.append(job_count)
        Benifits.append(benefits)

        pagenum.append(i)
 
    print(f'Page {i} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time)) 



data = pd.DataFrame({
    "Name": Name,
    "Ratings": Ratings,
    "Location": location,
    "Reviews": Reviews,
    "Salaries": Salaries,
    "Interviews": Interviews,
    "jobs":jobs,
    "Benifits":Benifits,
    "Awards":Awards,
     "Page Number": pagenum})

Page 1 completed in 4.13 seconds
Page 2 completed in 6.31 seconds
Page 3 completed in 1.49 seconds
Page 4 completed in 3.69 seconds
Page 5 completed in 0.47 seconds
Page 6 completed in 0.49 seconds
Page 7 completed in 0.45 seconds
Page 8 completed in 0.41 seconds
Page 9 completed in 0.44 seconds
Page 10 completed in 1.49 seconds
Total Time Completed in seconds 19.37980031967163

In [97]:
data

,Name,Ratings,Location,Reviews,Salaries,Interviews,jobs,Benifits,Awards,Page Number
0,TCS,3.3 \n\t\t\t\t\t\t\t\t\t(1.1L),IT Services & Consulting | Hyderabad / Secunde...,1.1L,9.9L,11.9k,3.3k,10.6k,NaN,1
1,Accenture,3.7 \n\t\t\t\t\t\t\t\t\t(72.1k),IT Services & Consulting | Hyderabad / Secunde...,72.1k,6.5L,9.2k,34.5k,6.7k,NaN,1
2,Wipro,3.6 \n\t\t\t\t\t\t\t\t\t(64k),IT Services & Consulting | Hyderabad +371 othe...,64k,4.8L,6.7k,4.7k,4.6k,NaN,1
3,Cognizant,3.6 \n\t\t\t\t\t\t\t\t\t(60.4k),IT Services & Consulting | Hyderabad +232 othe...,60.4k,6L,6.4k,552,5.5k,NaN,1
4,Capgemini,3.7 \n\t\t\t\t\t\t\t\t\t(52.1k),IT Services & Consulting | Hyderabad / Secunde...,52.1k,4.8L,5.5k,2.7k,3.7k,NaN,1
...,...,...,...,...,...,...,...,...,...,...
195,American Express,4.1 \n\t\t\t\t\t\t\t\t\t(3.8k),Financial Services | Hyderabad / Secunderabad ...,3.8k,25.3k,427,165,435,AmbitionBox Award Winner'25,10
196,Reliance Communications,4.0 \n\t\t\t\t\t\t\t\t\t(3.8k),Telecom | Hyderabad / Secunderabad +468 other ...,3.8k,9.6k,106,--,375,NaN,10
197,Aditya Birla Sun Life Insurance,4.0 \n\t\t\t\t\t\t\t\t\t(3.8k),Insurance | Hyderabad / Secunderabad +494 othe...,3.8k,10.1k,182,--,214,NaN,10
198,Carelon Global Solutions,3.9 \n\t\t\t\t\t\t\t\t\t(4.1k),IT Services & Consulting | Hyderabad / Secunde...,4.1k,28.3k,422,52,7,NaN,10
199,Grasim Industries,4.0 \n\t\t\t\t\t\t\t\t\t(3.8k),Building Material | Hyderabad / Secunderabad +...,3.8k,12.7k,277,6,267,NaN,10

In [2]:
data.to_csv("Ambitionbox_data.csv", index = False)

NameError: name 'data' is not defined

In [99]:
data.head()

,Name,Ratings,Location,Reviews,Salaries,Interviews,jobs,Benifits,Awards,Page Number
0,TCS,3.3 \n\t\t\t\t\t\t\t\t\t(1.1L),IT Services & Consulting | Hyderabad / Secunde...,1.1L,9.9L,11.9k,3.3k,10.6k,NaN,1
1,Accenture,3.7 \n\t\t\t\t\t\t\t\t\t(72.1k),IT Services & Consulting | Hyderabad / Secunde...,72.1k,6.5L,9.2k,34.5k,6.7k,NaN,1
2,Wipro,3.6 \n\t\t\t\t\t\t\t\t\t(64k),IT Services & Consulting | Hyderabad +371 othe...,64k,4.8L,6.7k,4.7k,4.6k,NaN,1
3,Cognizant,3.6 \n\t\t\t\t\t\t\t\t\t(60.4k),IT Services & Consulting | Hyderabad +232 othe...,60.4k,6L,6.4k,552,5.5k,NaN,1
4,Capgemini,3.7 \n\t\t\t\t\t\t\t\t\t(52.1k),IT Services & Consulting | Hyderabad / Secunde...,52.1k,4.8L,5.5k,2.7k,3.7k,NaN,1

In [100]:
data['Ratings'] = data['Ratings'].apply(lambda x:re.findall(r"^[\d.]+",x)[0]).astype("float")

In [102]:
data["Industry"] = data["Location"].apply(lambda x:re.split(r"[|]",x)[0])

In [89]:
data["No.of Braches"] = data["Location"].apply(lambda x:re.split(r"[+]",x)[1])

In [106]:
data["Branches"] = data["Location"].apply(lambda x:re.findall(r"\d+", x)[0]).astype("int")

In [109]:
data["Location"] = data["Location"].apply(lambda x:re.split(r"[|]",x)[1])

In [112]:
data["Location"] = data["Location"].apply(lambda x:re.split(r"[+]",x)[0])

In [1]:
data.head(20)

NameError: name 'data' is not defined

In [27]:
data.isnull().sum()

Name               0
Ratings            0
Location           0
Reviews            0
Salaries           0
Interviews         0
jobs               0
Benifits           0
Awards            93
Page Number        0
Services           0
No.of Braches      0
No.of Branches     0
dtype: int64

In [115]:
data["Awards"] = data["Awards"].fillna("No Award")

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            140 non-null    object
 1   Ratings         140 non-null    float64
 2   Location        140 non-null    object
 3   Reviews         140 non-null    object
 4   Salaries        140 non-null    object
 5   Interviews      140 non-null    object
 6   jobs            140 non-null    object
 7   Benifits        140 non-null    object
 8   Awards          47 non-null     object
 9   Page Number     140 non-null    int64
 10  Services        140 non-null    object
 11  No.of Braches   140 non-null    object
 12  No.of Branches  140 non-null    int64
dtypes: float64(1), int64(2), object(10)
memory usage: 14.3+ KB

In [31]:
data.shape

(140, 13)

In [33]:
data.describe()

          Ratings  Page Number  No.of Branches
count  140.000000   140.000000      140.000000
mean     3.795000     4.000000      389.878571
std      0.292182     2.007181      365.329879
min      3.100000     1.000000       26.000000
25%      3.600000     2.000000      109.750000
50%      3.800000     4.000000      265.000000
75%      4.000000     6.000000      554.250000
max      4.700000     7.000000     1966.000000

In [114]:
data.duplicated().sum()

np.int64(0)

In [37]:
data.columns

Index(['Name', 'Ratings', 'Location', 'Reviews', 'Salaries', 'Interviews',
       'jobs', 'Benifits', 'Awards', 'Page Number', 'Services',
       'No.of Braches', 'No.of Branches'],
      dtype='object')

In [38]:
#data.drop("No.of Braches", axis=1, inplace=True)

In [39]:
data.columns

Index(['Name', 'Ratings', 'Location', 'Reviews', 'Salaries', 'Interviews',
       'jobs', 'Benifits', 'Awards', 'Page Number', 'Services',
       'No.of Branches'],
      dtype='object')

In [120]:
data.head()

,Name,Ratings,Location,Reviews,Salaries,Interviews,jobs,Benifits,Awards,Industry,Branches
0,TCS,3.3,Hyderabad / Secunderabad,1.1L,9.9L,11.9k,3.3k,10.6k,No Award,IT Services & Consulting,439
1,Accenture,3.7,Hyderabad / Secunderabad,72.1k,6.5L,9.2k,34.5k,6.7k,No Award,IT Services & Consulting,255
2,Wipro,3.6,Hyderabad,64k,4.8L,6.7k,4.7k,4.6k,No Award,IT Services & Consulting,371
3,Cognizant,3.6,Hyderabad,60.4k,6L,6.4k,552,5.5k,No Award,IT Services & Consulting,232
4,Capgemini,3.7,Hyderabad / Secunderabad,52.1k,4.8L,5.5k,2.7k,3.7k,No Award,IT Services & Consulting,182

In [57]:
data.to_csv("cleaned_data.csv", index=False)
data

,Name,Ratings,Location,Reviews,Salaries,Interviews,jobs,Benifits,Awards
0,TCS,3.3 \n\t\t\t\t\t\t\t\t\t(1.1L),IT Services & Consulting | Hyderabad / Secunde...,1.1L,9.9L,11.9k,3.3k,10.6k,NaN
1,Accenture,3.7 \n\t\t\t\t\t\t\t\t\t(72.1k),IT Services & Consulting | Hyderabad / Secunde...,72.1k,6.5L,9.2k,34.5k,6.7k,NaN
2,Wipro,3.6 \n\t\t\t\t\t\t\t\t\t(64k),IT Services & Consulting | Hyderabad +371 othe...,64k,4.8L,6.7k,4.7k,4.6k,NaN
3,Cognizant,3.6 \n\t\t\t\t\t\t\t\t\t(60.4k),IT Services & Consulting | Hyderabad +232 othe...,60.4k,6L,6.4k,552,5.5k,NaN
4,Capgemini,3.7 \n\t\t\t\t\t\t\t\t\t(52.1k),IT Services & Consulting | Hyderabad / Secunde...,52.1k,4.8L,5.5k,2.7k,3.7k,NaN
...,...,...,...,...,...,...,...,...,...
175,Macleods Pharmaceuticals,3.7 \n\t\t\t\t\t\t\t\t\t(4.2k),Pharma | Hyderabad / Secunderabad +135 other l...,4.2k,15.6k,270,15,334,NaN
176,Jubilant Foods Works,3.7 \n\t\t\t\t\t\t\t\t\t(4.1k),Hospitality | Hyderabad / Secunderabad +262 ot...,4.1k,9.4k,253,248,180,NaN
177,Aakash Educational Services,3.2 \n\t\t\t\t\t\t\t\t\t(4.1k),Education & Training | Hyderabad / Secunderaba...,4.1k,13.8k,373,64,212,NaN
178,LG Electronics,3.9 \n\t\t\t\t\t\t\t\t\t(4.1k),Consumer Electronics & Appliances | Hyderabad ...,4.1k,11.2k,260,--,399,NaN
179,Hindalco Industries,4.2 \n\t\t\t\t\t\t\t\t\t(4.1k),Metals & Mining | Hyderabad / Secunderabad +12...,4.1k,12.6k,304,9,327,AmbitionBox Award Winner'25

In [46]:
data.shape

(140, 12)

In [51]:
data.describe(include = "all")

,Name,Ratings,Location,Reviews,Salaries,Interviews,jobs,Benifits,Awards,Page Number
count,180,180,180,180,180,180,180,180,51,180.000000
unique,180,154,178,88,150,155,129,153,1,NaN
top,TCS,3.9 \n\t\t\t\t\t\t\t\t\t(5.7k),IT Services & Consulting | Hyderabad / Secunde...,4.5k,13.4k,1.1k,--,1.1k,AmbitionBox Award Winner'25,NaN
freq,1,4,2,10,3,4,15,6,51,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.589191
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000

In [53]:
data.columns

Index(['Name', 'Ratings', 'Location', 'Reviews', 'Salaries', 'Interviews',
       'jobs', 'Benifits', 'Awards', 'Page Number'],
      dtype='object')

In [117]:
data.drop("Page Number", axis = 1,inplace = True)

In [119]:
data.head()
data.shape

(200, 11)

In [61]:
df = pd.read_csv("cleaned_data.csv")
df

,Name,Ratings,Location,Reviews,Salaries,Interviews,jobs,Benifits,Awards
0,TCS,3.3 \n\t\t\t\t\t\t\t\t\t(1.1L),IT Services & Consulting | Hyderabad / Secunde...,1.1L,9.9L,11.9k,3.3k,10.6k,NaN
1,Accenture,3.7 \n\t\t\t\t\t\t\t\t\t(72.1k),IT Services & Consulting | Hyderabad / Secunde...,72.1k,6.5L,9.2k,34.5k,6.7k,NaN
2,Wipro,3.6 \n\t\t\t\t\t\t\t\t\t(64k),IT Services & Consulting | Hyderabad +371 othe...,64k,4.8L,6.7k,4.7k,4.6k,NaN
3,Cognizant,3.6 \n\t\t\t\t\t\t\t\t\t(60.4k),IT Services & Consulting | Hyderabad +232 othe...,60.4k,6L,6.4k,552,5.5k,NaN
4,Capgemini,3.7 \n\t\t\t\t\t\t\t\t\t(52.1k),IT Services & Consulting | Hyderabad / Secunde...,52.1k,4.8L,5.5k,2.7k,3.7k,NaN
...,...,...,...,...,...,...,...,...,...
175,Macleods Pharmaceuticals,3.7 \n\t\t\t\t\t\t\t\t\t(4.2k),Pharma | Hyderabad / Secunderabad +135 other l...,4.2k,15.6k,270,15,334,NaN
176,Jubilant Foods Works,3.7 \n\t\t\t\t\t\t\t\t\t(4.1k),Hospitality | Hyderabad / Secunderabad +262 ot...,4.1k,9.4k,253,248,180,NaN
177,Aakash Educational Services,3.2 \n\t\t\t\t\t\t\t\t\t(4.1k),Education & Training | Hyderabad / Secunderaba...,4.1k,13.8k,373,64,212,NaN
178,LG Electronics,3.9 \n\t\t\t\t\t\t\t\t\t(4.1k),Consumer Electronics & Appliances | Hyderabad ...,4.1k,11.2k,260,--,399,NaN
179,Hindalco Industries,4.2 \n\t\t\t\t\t\t\t\t\t(4.1k),Metals & Mining | Hyderabad / Secunderabad +12...,4.1k,12.6k,304,9,327,AmbitionBox Award Winner'25

In [121]:
data.head()

,Name,Ratings,Location,Reviews,Salaries,Interviews,jobs,Benifits,Awards,Industry,Branches
0,TCS,3.3,Hyderabad / Secunderabad,1.1L,9.9L,11.9k,3.3k,10.6k,No Award,IT Services & Consulting,439
1,Accenture,3.7,Hyderabad / Secunderabad,72.1k,6.5L,9.2k,34.5k,6.7k,No Award,IT Services & Consulting,255
2,Wipro,3.6,Hyderabad,64k,4.8L,6.7k,4.7k,4.6k,No Award,IT Services & Consulting,371
3,Cognizant,3.6,Hyderabad,60.4k,6L,6.4k,552,5.5k,No Award,IT Services & Consulting,232
4,Capgemini,3.7,Hyderabad / Secunderabad,52.1k,4.8L,5.5k,2.7k,3.7k,No Award,IT Services & Consulting,182

In [137]:
import pandas as pd

def convert_value(x):
    x = str(x).lower()
    
    if 'k' in x:
        return float(x.replace('k','')) * 1000
    elif 'l' in x:
        return float(x.replace('l','')) * 100000
    else:
        return float(x)

cols = ['Reviews','Salaries','Interviews','jobs','Benifits']

for c in cols:
    data[c] = data[c].apply(convert_value)

In [127]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        200 non-null    object
 1   Ratings     200 non-null    float64
 2   Location    200 non-null    object
 3   Reviews     200 non-null    float64
 4   Salaries    200 non-null    float64
 5   Interviews  200 non-null    float64
 6   jobs        200 non-null    object
 7   Benifits    200 non-null    object
 8   Awards      200 non-null    object
 9   Industry    200 non-null    object
 10  Branches    200 non-null    int64
dtypes: float64(4), int64(1), object(6)
memory usage: 17.3+ KB

In [132]:
data["jobs"].tail(20)

180     43
181     17
182      8
183     23
184    261
185     60
186      2
187     34
188     80
189    220
190     --
191     13
192     87
193    172
194      1
195    165
196     --
197     --
198     52
199      6
Name: jobs, dtype: object

In [133]:
data= data.replace('--', pd.NA)

In [134]:
data.isnull().sum()

Name           0
Ratings        0
Location       0
Reviews        0
Salaries       0
Interviews     0
jobs          18
Benifits       0
Awards         0
Industry       0
Branches       0
dtype: int64

In [135]:
data["jobs"].fillna(data["jobs"].mode()[0], inplace=True)

In [136]:
data.isnull().sum()

Name          0
Ratings       0
Location      0
Reviews       0
Salaries      0
Interviews    0
jobs          0
Benifits      0
Awards        0
Industry      0
Branches      0
dtype: int64

In [138]:
data.head()

,Name,Ratings,Location,Reviews,Salaries,Interviews,jobs,Benifits,Awards,Industry,Branches
0,TCS,3.3,Hyderabad / Secunderabad,110000.0,990000.0,11900.0,3300.0,10600.0,No Award,IT Services & Consulting,439
1,Accenture,3.7,Hyderabad / Secunderabad,72100.0,650000.0,9200.0,34500.0,6700.0,No Award,IT Services & Consulting,255
2,Wipro,3.6,Hyderabad,64000.0,480000.0,6700.0,4700.0,4600.0,No Award,IT Services & Consulting,371
3,Cognizant,3.6,Hyderabad,60400.0,600000.0,6400.0,552.0,5500.0,No Award,IT Services & Consulting,232
4,Capgemini,3.7,Hyderabad / Secunderabad,52100.0,480000.0,5500.0,2700.0,3700.0,No Award,IT Services & Consulting,182

In [143]:
data.to_csv("cleaned.csv", index = False)

In [141]:
data = data[["Name","Industry","Location","Branches","Ratings","Reviews","Salaries","Interviews","jobs","Benifits","Awards"]]

In [142]:
data

,Name,Industry,Location,Branches,Ratings,Reviews,Salaries,Interviews,jobs,Benifits,Awards
0,TCS,IT Services & Consulting,Hyderabad / Secunderabad,439,3.3,110000.0,990000.0,11900.0,3300.0,10600.0,No Award
1,Accenture,IT Services & Consulting,Hyderabad / Secunderabad,255,3.7,72100.0,650000.0,9200.0,34500.0,6700.0,No Award
2,Wipro,IT Services & Consulting,Hyderabad,371,3.6,64000.0,480000.0,6700.0,4700.0,4600.0,No Award
3,Cognizant,IT Services & Consulting,Hyderabad,232,3.6,60400.0,600000.0,6400.0,552.0,5500.0,No Award
4,Capgemini,IT Services & Consulting,Hyderabad / Secunderabad,182,3.7,52100.0,480000.0,5500.0,2700.0,3700.0,No Award
...,...,...,...,...,...,...,...,...,...,...,...
195,American Express,Financial Services,Hyderabad / Secunderabad,53,4.1,3800.0,25300.0,427.0,165.0,435.0,AmbitionBox Award Winner'25
196,Reliance Communications,Telecom,Hyderabad / Secunderabad,468,4.0,3800.0,9600.0,106.0,4.0,375.0,No Award
197,Aditya Birla Sun Life Insurance,Insurance,Hyderabad / Secunderabad,494,4.0,3800.0,10100.0,182.0,4.0,214.0,No Award
198,Carelon Global Solutions,IT Services & Consulting,Hyderabad / Secunderabad,21,3.9,4100.0,28300.0,422.0,52.0,7.0,No Award
199,Grasim Industries,Building Material,Hyderabad / Secunderabad,247,4.0,3800.0,12700.0,277.0,6.0,267.0,No Award

In [144]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        200 non-null    object
 1   Industry    200 non-null    object
 2   Location    200 non-null    object
 3   Branches    200 non-null    int64
 4   Ratings     200 non-null    float64
 5   Reviews     200 non-null    float64
 6   Salaries    200 non-null    float64
 7   Interviews  200 non-null    float64
 8   jobs        200 non-null    float64
 9   Benifits    200 non-null    float64
 10  Awards      200 non-null    object
dtypes: float64(6), int64(1), object(4)
memory usage: 17.3+ KB